export const FILE_CHANGE = 'Cambiar archivo'
export const FILE_ERROR = 'Abrir archivo'
export const NO_FILE = 'Sin archivo'
export const RELOAD_PETITION = 'Recargar para cambiar de imagen'
export const CLEAN_IMAGE = 'Borrar imagen'
